# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-03-20 20:59
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('login_registration', '0001_initial'),
        ('courses_app', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='course',
            name='users',
            field=models.ManyToManyField(related_name='Courses', to='login_registration.User'),
        ),
    ]
