# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-03-20 20:59
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses_app', '0002_course_users'),
    ]

    operations = [
        migrations.AlterField(
            model_name='course',
            name='users',
            field=models.ManyToManyField(related_name='courses', to='login_registration.User'),
        ),
    ]
